# E-Commerce Order Analytics System

## Week 8 Intern Mini Project

# Technologies
- Python
- Pandas
- SQLite
- SQL
- Jupyter Notebook

### Project Objective
To clean, transform and analyze e-commerce order data
and generate business analytics reports.

In [2]:
import pandas as pd
import numpy as np
import random
import string
import os
import sqlite3
from datetime import datetime, timedelta

print("Libraries imported successfully!")

Libraries imported successfully!

In [6]:
os.makedirs("data", exist_ok=True)
os.makedirs("reports", exist_ok=True)

In [8]:
## 1.Customers Dataset
# Number of customers
num_customers = 500

customer_types = ["REGULAR", "PREMIUM", "VIP"]

first_names = [
    "Aarav", "Vivaan", "Aditya", "Arjun", "Rahul",
    "Rohan", "Karan", "Ananya", "Priya", "Sneha",
    "Isha", "Neha", "Pooja", "Aditi", "Kavya"
]

last_names = [
    "Sharma", "Patil", "Deshmukh", "Joshi", "Kulkarni",
    "Mehta", "Shah", "Verma", "Gupta", "Singh"
]

customers = []

for i in range(1, num_customers + 1):

    customer_id = f"C{i:04d}"

    name = random.choice(first_names) + " " + random.choice(last_names)

    email = (
        name.lower()
        .replace(" ", ".")
        + str(random.randint(1, 999))
        + "@gmail.com"
    )

    # Approximately 2% invalid emails
    if i % 50 == 0:
        email = email.replace("@", "")

    registration_date = (
        datetime.now() - timedelta(days=random.randint(1, 1000))
    ).strftime("%Y-%m-%d")

    customer_type = random.choice(customer_types)

    customers.append([
        customer_id,
        name,
        email,
        registration_date,
        customer_type
    ])

customers_df = pd.DataFrame(
    customers,
    columns=[
        "customer_id",
        "customer_name",
        "email",
        "registration_date",
        "customer_type"
    ]
)

customers_df.to_csv(
    "data/customers.csv",
    index=False
)

print("Customers generated:", len(customers_df))
customers_df.head()

Customers generated: 500

,customer_id,customer_name,email,registration_date,customer_type
0,C0001,Pooja Mehta,pooja.mehta812@gmail.com,2024-09-10,VIP
1,C0002,Rahul Shah,rahul.shah459@gmail.com,2026-01-29,REGULAR
2,C0003,Vivaan Kulkarni,vivaan.kulkarni773@gmail.com,2024-02-22,VIP
3,C0004,Rohan Sharma,rohan.sharma605@gmail.com,2026-01-08,REGULAR
4,C0005,Priya Shah,priya.shah726@gmail.com,2024-12-21,PREMIUM

In [11]:
## 2.Products Dataset
num_products = 500

categories = {
    "Electronics": ["Laptop", "Mobile", "Headphones", "Camera", "Keyboard"],
    "Clothing": ["T-Shirt", "Jeans", "Jacket", "Shoes", "Dress"],
    "Home": ["Chair", "Table", "Lamp", "Curtains", "Cushion"],
    "Books": ["Novel", "Textbook", "Biography", "Comics", "Dictionary"]
}

products = []

for i in range(1, num_products + 1):

    product_id = f"P{i:04d}"

    category = random.choice(list(categories.keys()))
    product_name = random.choice(categories[category])

    # Add intentional data-quality problems
    if i % 20 == 0:
        product_name = "  " + product_name.lower() + "  "
    elif i % 25 == 0:
        product_name = product_name.upper()

    subcategory = category + " Products"

    cost_price = round(random.uniform(100, 5000), 2)

    products.append([
        product_id,
        product_name,
        category,
        subcategory,
        cost_price
    ])

products_df = pd.DataFrame(
    products,
    columns=[
        "product_id",
        "product_name",
        "category",
        "subcategory",
        "cost_price"
    ]
)

products_df.to_csv(
    "data/products.csv",
    index=False
)

print("Products generated:", len(products_df))
products_df.head()

Products generated: 500

  product_id product_name     category           subcategory  cost_price
0      P0001       Comics        Books        Books Products     3570.45
1      P0002       Camera  Electronics  Electronics Products     1680.74
2      P0003     Curtains         Home         Home Products     4506.52
3      P0004        Table         Home         Home Products      617.65
4      P0005        Jeans     Clothing     Clothing Products     2097.56

In [13]:
# 3.Orders Dataset
num_orders = 1000

statuses = [
    "PLACED",
    "SHIPPED",
    "DELIVERED",
    "CANCELLED",
    "RETURNED"
]

regions = ["NORTH", "SOUTH", "EAST", "WEST"]

order_ids = []
orders = []

for i in range(1, num_orders + 1):

    order_id = f"O{i:05d}"
    order_ids.append(order_id)

    # 5% missing customer IDs
    if i % 20 == 0:
        customer_id = None
    else:
        customer_id = random.choice(customers_df["customer_id"].tolist())

    order_date = datetime.now() - timedelta(
        days=random.randint(1, 450),
        hours=random.randint(0, 23),
        minutes=random.randint(0, 59)
    )

    order_date_str = order_date.strftime("%Y-%m-%d %H:%M:%S")

    # Some dates intentionally in DD-MM-YYYY format
    if i % 100 == 0:
        order_date_str = order_date.strftime("%d-%m-%Y")

    status = random.choice(statuses)
    region = random.choice(regions)

    orders.append([
        order_id,
        customer_id,
        order_date_str,
        status,
        region
    ])

orders_df = pd.DataFrame(
    orders,
    columns=[
        "order_id",
        "customer_id",
        "order_date",
        "status",
        "region_code"
    ]
)

orders_df.to_csv(
    "data/orders.csv",
    index=False
)

print("Orders generated:", len(orders_df))
orders_df.head()

Orders generated: 1000

  order_id customer_id           order_date    status region_code
0   O00001       C0195  2025-10-20 13:13:58  RETURNED        WEST
1   O00002       C0309  2026-07-14 13:04:58    PLACED        EAST
2   O00003       C0198  2025-06-17 03:19:58    PLACED        EAST
3   O00004       C0452  2025-07-28 13:58:58    PLACED       NORTH
4   O00005       C0485  2026-02-18 18:47:58  RETURNED       NORTH

In [15]:
# 4.Order Items Dataset
num_items = 2000

product_ids = products_df["product_id"].tolist()

order_items = []

for i in range(1, num_items + 1):

    item_id = f"I{i:05d}"

    # Select an existing order
    order_id = random.choice(order_ids)

    product_id = random.choice(product_ids)

    quantity = random.randint(1, 5)

    # Approximately 3% negative quantities
    if i % 33 == 0:
        quantity = -quantity

    unit_price = round(random.uniform(200, 10000), 2)

    discount_percent = round(
        random.uniform(0, 100), 2
    )

    order_items.append([
        item_id,
        order_id,
        product_id,
        quantity,
        unit_price,
        discount_percent
    ])

order_items_df = pd.DataFrame(
    order_items,
    columns=[
        "item_id",
        "order_id",
        "product_id",
        "quantity",
        "unit_price",
        "discount_percent"
    ]
)

order_items_df.to_csv(
    "data/order_items.csv",
    index=False
)

print("Order items generated:", len(order_items_df))
order_items_df.head()

Order items generated: 2000

  item_id order_id product_id  quantity  unit_price  discount_percent
0  I00001   O00684      P0068         5      575.51             20.55
1  I00002   O00969      P0360         5     4282.24             99.29
2  I00003   O00415      P0040         3     4611.58             19.33
3  I00004   O00421      P0133         4     2578.57             59.98
4  I00005   O00627      P0332         2     3822.56             80.48

In [17]:
print("Customers:", len(customers_df))
print("Products:", len(products_df))
print("Orders:", len(orders_df))
print("Order Items:", len(order_items_df))

Customers: 500
Products: 500
Orders: 1000
Order Items: 2000

In [19]:
print(os.listdir("data"))

['customers.csv', 'orders.csv', 'order_items.csv', 'products.csv']

In [21]:
missing_customers = orders_df["customer_id"].isna().sum()

print("Missing customer IDs:", missing_customers)

Missing customer IDs: 50

In [23]:
negative_quantities = (
    order_items_df["quantity"] < 0
).sum()

print("Negative quantities:", negative_quantities)

Negative quantities: 60

In [25]:
email_pattern = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"

invalid_emails = (
    ~customers_df["email"].str.match(
        email_pattern,
        na=False
    )
).sum()

print("Invalid emails:", invalid_emails)

Invalid emails: 10

## Step 2: Data cleaning

In [31]:
# Load raw datasets

orders_df = pd.read_csv("data/orders.csv")
order_items_df = pd.read_csv("data/order_items.csv")
products_df = pd.read_csv("data/products.csv")
customers_df = pd.read_csv("data/customers.csv")

print("All datasets loaded successfully!")

print("\nDataset sizes:")
print("Orders:", orders_df.shape)
print("Order Items:", order_items_df.shape)
print("Products:", products_df.shape)
print("Customers:", customers_df.shape)

All datasets loaded successfully!

Dataset sizes:
Orders: (1000, 5)
Order Items: (2000, 6)
Products: (500, 5)
Customers: (500, 5)

In [33]:
print("Missing customer IDs:")
print(orders_df["customer_id"].isna().sum())

print("\nNegative quantities:")
print((order_items_df["quantity"] < 0).sum())

print("\nPotential invalid emails:")

email_pattern = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"

invalid_email_count = (
    ~customers_df["email"].str.match(
        email_pattern,
        na=False
    )
).sum()

print(invalid_email_count)

print("\nSample product names:")
print(products_df["product_name"].head(15).to_list())

print("\nSample order dates:")
print(orders_df["order_date"].head(10).to_list())

Missing customer IDs:
50

Negative quantities:
60

Potential invalid emails:
10

Sample product names:
['Comics', 'Camera', 'Curtains', 'Table', 'Jeans', 'Jeans', 'Curtains', 'Mobile', 'Jacket', 'Dictionary', 'Jacket', 'Novel', 'Dictionary', 'Keyboard', 'Comics']

Sample order dates:
['2025-10-20 13:13:58', '2026-07-14 13:04:58', '2025-06-17 03:19:58', '2025-07-28 13:58:58', '2026-02-18 18:47:58', '2025-09-04 09:52:58', '2025-07-31 23:30:58', '2026-05-06 14:42:58', '2026-02-10 04:02:58', '2025-09-15 05:43:58']

In [37]:
def clean_orders(df):
    """
    Cleans the orders dataset.

    Operations:
    1. Convert all order dates to YYYY-MM-DD HH:MM:SS
    2. Preserve missing customer IDs as NULL
    3. Remove duplicate orders
    """
    
    cleaned = df.copy()

    # Count missing customer IDs before cleaning
    missing_customer_count = cleaned["customer_id"].isna().sum()

    # Convert dates.
    # dayfirst=True allows DD-MM-YYYY values to be interpreted correctly.
    cleaned["order_date"] = pd.to_datetime(
        cleaned["order_date"],
        dayfirst=True,
        errors="coerce"
    )

    # Convert dates to standard format
    cleaned["order_date"] = cleaned["order_date"].dt.strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    # Keep missing customer IDs as NULL
    cleaned["customer_id"] = cleaned["customer_id"].replace(
        ["", "NULL", "null", "None"],
        np.nan
    )

    # Remove duplicate order IDs
    duplicate_orders = cleaned["order_id"].duplicated().sum()

    cleaned = cleaned.drop_duplicates(
        subset=["order_id"]
    )

    return cleaned, missing_customer_count, duplicate_orders

In [39]:
orders_cleaned, missing_customers, duplicate_orders = clean_orders(
    orders_df
)

print("Orders cleaned successfully!")
print("Missing customer IDs:", missing_customers)
print("Duplicate orders removed:", duplicate_orders)

orders_cleaned.head()

Orders cleaned successfully!
Missing customer IDs: 50
Duplicate orders removed: 0

C:\Users\anush\AppData\Local\Temp\ipykernel_13236\27329138.py:18: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  cleaned["order_date"] = pd.to_datetime(

  order_id customer_id           order_date    status region_code
0   O00001       C0195  2025-10-20 13:13:58  RETURNED        WEST
1   O00002       C0309  2026-07-14 13:04:58    PLACED        EAST
2   O00003       C0198  2025-06-17 03:19:58    PLACED        EAST
3   O00004       C0452  2025-07-28 13:58:58    PLACED       NORTH
4   O00005       C0485  2026-02-18 18:47:58  RETURNED       NORTH

In [41]:
print(
    orders_cleaned["order_date"].head(10)
)

0    2025-10-20 13:13:58
1    2026-07-14 13:04:58
2    2025-06-17 03:19:58
3    2025-07-28 13:58:58
4    2026-02-18 18:47:58
5    2025-09-04 09:52:58
6    2025-07-31 23:30:58
7    2026-05-06 14:42:58
8    2026-02-10 04:02:58
9    2025-09-15 05:43:58
Name: order_date, dtype: object

In [43]:
## 8. Clean Products Dataset
def clean_products(df):
    """
    Cleans product names by:
    - Removing leading/trailing spaces
    - Converting names to title case
    """
    
    cleaned = df.copy()

    # Count product names that need cleaning
    original_names = cleaned["product_name"].copy()

    # Remove extra spaces
    cleaned["product_name"] = (
        cleaned["product_name"]
        .astype(str)
        .str.strip()
    )

    # Normalize capitalization
    cleaned["product_name"] = (
        cleaned["product_name"]
        .str.title()
    )

    changed_names = (
        original_names != cleaned["product_name"]
    ).sum()

    return cleaned, changed_names

In [45]:
products_cleaned, changed_product_names = clean_products(
    products_df
)

print("Products cleaned successfully!")
print("Product names normalized:", changed_product_names)

products_cleaned.head(15)

Products cleaned successfully!
Product names normalized: 40

   product_id product_name     category           subcategory  cost_price
0       P0001       Comics        Books        Books Products     3570.45
1       P0002       Camera  Electronics  Electronics Products     1680.74
2       P0003     Curtains         Home         Home Products     4506.52
3       P0004        Table         Home         Home Products      617.65
4       P0005        Jeans     Clothing     Clothing Products     2097.56
5       P0006        Jeans     Clothing     Clothing Products     3974.25
6       P0007     Curtains         Home         Home Products     2502.95
7       P0008       Mobile  Electronics  Electronics Products      389.28
8       P0009       Jacket     Clothing     Clothing Products     3139.18
9       P0010   Dictionary        Books        Books Products     4921.96
10      P0011       Jacket     Clothing     Clothing Products     3344.04
11      P0012        Novel        Books        Books Products     4170.96
12      P0013   Dictionary        Books        Books Products     4201.90
13      P0014     Keyboard  Electronics  Electronics Products     4106.66
14      P0015       Comics        Books        Books Products     4421.00

In [47]:
## 9. Validate Customer Emails
def validate_emails(df):
    """
    Returns customer IDs with invalid email addresses.
    """
    
    email_pattern = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"

    valid_email = df["email"].astype(str).str.match(
        email_pattern,
        na=False
    )

    invalid_customer_ids = df.loc[
        ~valid_email,
        "customer_id"
    ].tolist()

    return invalid_customer_ids

In [49]:
invalid_customer_ids = validate_emails(
    customers_df
)

print("Invalid email count:", len(invalid_customer_ids))

print("\nInvalid customer IDs:")
print(invalid_customer_ids)

Invalid email count: 10

Invalid customer IDs:
['C0050', 'C0100', 'C0150', 'C0200', 'C0250', 'C0300', 'C0350', 'C0400', 'C0450', 'C0500']

In [51]:
## 10. Check Referential Integrity
def check_referential_integrity(
    orders_df,
    order_items_df
):
    """
    Finds order items whose order_id
    does not exist in the orders dataset.
    """

    valid_order_ids = set(
        orders_df["order_id"]
    )

    invalid_items = order_items_df[
        ~order_items_df["order_id"].isin(
            valid_order_ids
        )
    ]

    return invalid_items

In [53]:
invalid_order_items = check_referential_integrity(
    orders_cleaned,
    order_items_df
)

print(
    "Referential integrity issues:",
    len(invalid_order_items)
)

invalid_order_items.head()

Referential integrity issues: 0

Empty DataFrame
Columns: [item_id, order_id, product_id, quantity, unit_price, discount_percent]
Index: []

In [59]:
## 11. Clean Order Items Dataset
def clean_order_items(df):
    cleaned = df.copy()

    # Convert numeric columns
    cleaned["quantity"] = pd.to_numeric(
        cleaned["quantity"],
        errors="coerce"
    )

    cleaned["unit_price"] = pd.to_numeric(
        cleaned["unit_price"],
        errors="coerce"
    )

    cleaned["discount_percent"] = pd.to_numeric(
        cleaned["discount_percent"],
        errors="coerce"
    )

    # Remove exact duplicate rows
    cleaned = cleaned.drop_duplicates()

    return cleaned

In [61]:
order_items_cleaned = clean_order_items(
    order_items_df
)

print("Order items cleaned successfully!")
print(order_items_cleaned.shape)

order_items_cleaned.head()

Order items cleaned successfully!
(2000, 6)

  item_id order_id product_id  quantity  unit_price  discount_percent
0  I00001   O00684      P0068         5      575.51             20.55
1  I00002   O00969      P0360         5     4282.24             99.29
2  I00003   O00415      P0040         3     4611.58             19.33
3  I00004   O00421      P0133         4     2578.57             59.98
4  I00005   O00627      P0332         2     3822.56             80.48

In [63]:
orders_cleaned.to_csv(
    "data/orders_cleaned.csv",
    index=False
)

order_items_cleaned.to_csv(
    "data/order_items_cleaned.csv",
    index=False
)

products_cleaned.to_csv(
    "data/products_cleaned.csv",
    index=False
)

customers_df.to_csv(
    "data/customers_cleaned.csv",
    index=False
)

print("All cleaned datasets saved successfully!")

All cleaned datasets saved successfully!

In [65]:
## 13. Data Quality Report

In [67]:
report = f"""
========================================
E-COMMERCE DATA QUALITY REPORT
========================================

RAW DATA
----------------------------------------
Customers       : {len(customers_df)}
Products        : {len(products_df)}
Orders          : {len(orders_df)}
Order Items     : {len(order_items_df)}

DATA QUALITY ISSUES
----------------------------------------
Missing customer IDs     : {missing_customers}
Negative quantities      : {(order_items_df["quantity"] < 0).sum()}
Invalid emails           : {len(invalid_customer_ids)}
Product names normalized : {changed_product_names}
Duplicate orders removed : {duplicate_orders}
Invalid order references : {len(invalid_order_items)}

CLEANED DATA
----------------------------------------
Customers       : {len(customers_df)}
Products        : {len(products_cleaned)}
Orders          : {len(orders_cleaned)}
Order Items     : {len(order_items_cleaned)}

========================================
END OF REPORT
========================================
"""

print(report)

========================================
E-COMMERCE DATA QUALITY REPORT
========================================

RAW DATA
----------------------------------------
Customers       : 500
Products        : 500
Orders          : 1000
Order Items     : 2000

DATA QUALITY ISSUES
----------------------------------------
Missing customer IDs     : 50
Negative quantities      : 60
Invalid emails           : 10
Product names normalized : 40
Duplicate orders removed : 0
Invalid order references : 0

CLEANED DATA
----------------------------------------
Customers       : 500
Products        : 500
Orders          : 1000
Order Items     : 2000

========================================
END OF REPORT
========================================

In [69]:
with open(
    "reports/data_quality_report.txt",
    "w"
) as file:
    file.write(report)

print("Data quality report saved successfully!")

Data quality report saved successfully!

In [71]:

print(
    "Orders cleaned:",
    os.path.exists("data/orders_cleaned.csv")
)

print(
    "Order items cleaned:",
    os.path.exists("data/order_items_cleaned.csv")
)

print(
    "Products cleaned:",
    os.path.exists("data/products_cleaned.csv")
)

print(
    "Customers cleaned:",
    os.path.exists("data/customers_cleaned.csv")
)

print(
    "Quality report:",
    os.path.exists("reports/data_quality_report.txt")
)

========== FINAL CHECK ==========
Orders cleaned: True
Order items cleaned: True
Products cleaned: True
Customers cleaned: True
Quality report: True

## STAGE 3 — Create the SQLite Database

In [74]:
import sqlite3

# Create/connect to SQLite database
connection = sqlite3.connect("ecommerce.db")

print("SQLite database connected successfully!")

SQLite database connected successfully!

In [76]:
## Load Cleaned Data into Pandas
customers_cleaned = pd.read_csv(
    "data/customers_cleaned.csv"
)

products_cleaned = pd.read_csv(
    "data/products_cleaned.csv"
)

orders_cleaned = pd.read_csv(
    "data/orders_cleaned.csv"
)

order_items_cleaned = pd.read_csv(
    "data/order_items_cleaned.csv"
)

print("Cleaned datasets loaded successfully!")

Cleaned datasets loaded successfully!

In [78]:
## Create SQLite Tables
customers_cleaned.to_sql(
    "customers",
    connection,
    if_exists="replace",
    index=False
)

products_cleaned.to_sql(
    "products",
    connection,
    if_exists="replace",
    index=False
)

orders_cleaned.to_sql(
    "orders",
    connection,
    if_exists="replace",
    index=False
)

order_items_cleaned.to_sql(
    "order_items",
    connection,
    if_exists="replace",
    index=False
)

print("All four tables created successfully!")

All four tables created successfully!

In [80]:
## Verify Database Tables
tables = pd.read_sql_query(
    """
    SELECT name
    FROM sqlite_master
    WHERE type = 'table'
    ORDER BY name;
    """,
    connection
)

tables

          name
0    customers
1  order_items
2       orders
3     products

In [82]:
for table in [
    "customers",
    "products",
    "orders",
    "order_items"
]:
    
    count = pd.read_sql_query(
        f"SELECT COUNT(*) AS count FROM {table}",
        connection
    )
    
    print(
        table,
        "→",
        count["count"].iloc[0],
        "records"
    )

customers → 500 records
products → 500 records
orders → 1000 records
order_items → 2000 records

In [84]:
pd.read_sql_query(
    """
    SELECT *
    FROM orders
    LIMIT 10;
    """,
    connection
)

  order_id customer_id           order_date    status region_code
0   O00001       C0195  2025-10-20 13:13:58  RETURNED        WEST
1   O00002       C0309  2026-07-14 13:04:58    PLACED        EAST
2   O00003       C0198  2025-06-17 03:19:58    PLACED        EAST
3   O00004       C0452  2025-07-28 13:58:58    PLACED       NORTH
4   O00005       C0485  2026-02-18 18:47:58  RETURNED       NORTH
5   O00006       C0481  2025-09-04 09:52:58    PLACED       SOUTH
6   O00007       C0015  2025-07-31 23:30:58    PLACED       SOUTH
7   O00008       C0151  2026-05-06 14:42:58    PLACED       NORTH
8   O00009       C0306  2026-02-10 04:02:58  RETURNED        EAST
9   O00010       C0315  2025-09-15 05:43:58  RETURNED        WEST

In [86]:
pd.read_sql_query(
    """
    SELECT *
    FROM order_items
    LIMIT 10;
    """,
    connection
)

  item_id order_id product_id  quantity  unit_price  discount_percent
0  I00001   O00684      P0068         5      575.51             20.55
1  I00002   O00969      P0360         5     4282.24             99.29
2  I00003   O00415      P0040         3     4611.58             19.33
3  I00004   O00421      P0133         4     2578.57             59.98
4  I00005   O00627      P0332         2     3822.56             80.48
5  I00006   O00472      P0034         1     6175.12             73.32
6  I00007   O00710      P0089         4     6236.12             15.74
7  I00008   O00492      P0339         4     7008.24             69.11
8  I00009   O00840      P0494         1     9589.55              6.85
9  I00010   O00976      P0034         4     9197.93              9.65

In [88]:
#Step 9 — Verify the relationship between orders and order_items
query = """
SELECT COUNT(*) AS invalid_order_items
FROM order_items oi
LEFT JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.order_id IS NULL;
"""

result = pd.read_sql_query(
    query,
    connection
)

result

   invalid_order_items
0                    0

In [90]:
#Step 10 — Verify products
query = """
SELECT COUNT(*) AS invalid_products
FROM order_items oi
LEFT JOIN products p
    ON oi.product_id = p.product_id
WHERE p.product_id IS NULL;
"""

result = pd.read_sql_query(
    query,
    connection
)

result

   invalid_products
0                 0

In [92]:
#Step 11 — Verify customers
query = """
SELECT COUNT(*) AS invalid_customers
FROM orders o
LEFT JOIN customers c
    ON o.customer_id = c.customer_id
WHERE o.customer_id IS NOT NULL
  AND c.customer_id IS NULL;
"""

result = pd.read_sql_query(
    query,
    connection
)

result

   invalid_customers
0                  0

In [94]:
#Step 12 — Create a useful database summary
summary_query = """
SELECT
    (SELECT COUNT(*) FROM customers) AS customers,
    (SELECT COUNT(*) FROM products) AS products,
    (SELECT COUNT(*) FROM orders) AS orders,
    (SELECT COUNT(*) FROM order_items) AS order_items;
"""

database_summary = pd.read_sql_query(
    summary_query,
    connection
)

database_summary

   customers  products  orders  order_items
0        500       500    1000         2000

In [96]:
#Step 13 — First actual business SQL query
query = """
SELECT
    p.category,
    ROUND(
        SUM(
            oi.quantity *
            oi.unit_price *
            (1 - oi.discount_percent / 100.0)
        ),
        2
    ) AS total_revenue
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;
"""

revenue_by_category = pd.read_sql_query(
    query,
    connection
)

revenue_by_category

      category  total_revenue
0  Electronics     4435402.12
1        Books     3597570.51
2     Clothing     3283522.26
3         Home     2862620.89

In [98]:
#Step 14 — Save this result
revenue_by_category.to_csv(
    "reports/revenue_by_category.csv",
    index=False
)

print("Revenue analysis saved.")

Revenue analysis saved.

## STEP 4 — Basic SQL Analytics

In [110]:
import sqlite3
import pandas as pd

connection = sqlite3.connect("ecommerce.db")

print("SQLite database reconnected successfully!")

SQLite database reconnected successfully!

In [112]:
connection

In [114]:
query = """
SELECT
    c.customer_id,
    c.customer_name,
    ROUND(
        SUM(
            oi.quantity *
            oi.unit_price *
            (1 - oi.discount_percent / 100.0)
        ),
        2
    ) AS total_order_value
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY
    c.customer_id,
    c.customer_name
ORDER BY total_order_value DESC
LIMIT 10;
"""

top_10_customers = pd.read_sql_query(
    query,
    connection
)

top_10_customers

  customer_id   customer_name  total_order_value
0       C0295     Kavya Verma          217965.86
1       C0216  Kavya Deshmukh          177738.03
2       C0315     Aditi Singh          148693.73
3       C0444     Rohan Patil          147108.06
4       C0435     Aarav Gupta          140000.07
5       C0381     Pooja Gupta          127714.60
6       C0363      Isha Patil          120532.96
7       C0324  Karan Deshmukh          116688.01
8       C0351     Kavya Mehta          111226.95
9       C0233    Aditya Joshi          110281.16

In [116]:
top_10_customers.to_csv(
    "reports/top_10_customers.csv",
    index=False
)

print("Top 10 customer report saved.")

Top 10 customer report saved.

In [118]:
#Query 3 — Month-wise Order Count
query = """
SELECT
    strftime('%Y-%m', order_date) AS order_month,
    COUNT(*) AS order_count
FROM orders
WHERE order_date >= date('now', '-12 months')
GROUP BY order_month
ORDER BY order_month;
"""

monthly_orders = pd.read_sql_query(
    query,
    connection
)

monthly_orders

   order_month  order_count
0      2025-08           49
1      2025-09           61
2      2025-10           75
3      2025-11           61
4      2025-12           66
5      2026-01           73
6      2026-02           64
7      2026-03           66
8      2026-04           59
9      2026-05           50
10     2026-06           51
11     2026-07           74
12     2026-08           18

In [120]:
monthly_orders.to_csv(
    "reports/monthly_order_count.csv",
    index=False
)

print("Monthly order report saved.")

Monthly order report saved.

In [122]:
#Basic SQL Analysis Summary
print("========== BASIC SQL ANALYSIS ==========\n")

print("1. Revenue by Category")
display(revenue_by_category)

print("\n2. Top 10 Customers")
display(top_10_customers)

print("\n3. Monthly Order Count")
display(monthly_orders)

========== BASIC SQL ANALYSIS ==========

1. Revenue by Category

      category  total_revenue
0  Electronics     4435402.12
1        Books     3597570.51
2     Clothing     3283522.26
3         Home     2862620.89

2. Top 10 Customers

  customer_id   customer_name  total_order_value
0       C0295     Kavya Verma          217965.86
1       C0216  Kavya Deshmukh          177738.03
2       C0315     Aditi Singh          148693.73
3       C0444     Rohan Patil          147108.06
4       C0435     Aarav Gupta          140000.07
5       C0381     Pooja Gupta          127714.60
6       C0363      Isha Patil          120532.96
7       C0324  Karan Deshmukh          116688.01
8       C0351     Kavya Mehta          111226.95
9       C0233    Aditya Joshi          110281.16

3. Monthly Order Count

   order_month  order_count
0      2025-08           49
1      2025-09           61
2      2025-10           75
3      2025-11           61
4      2025-12           66
5      2026-01           73
6      2026-02           64
7      2026-03           66
8      2026-04           59
9      2026-05           50
10     2026-06           51
11     2026-07           74
12     2026-08           18

In [124]:
query = """
SELECT
    c.customer_id,
    c.customer_name
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.customer_name
HAVING
    SUM(
        CASE
            WHEN o.status = 'DELIVERED'
            THEN 1
            ELSE 0
        END
    ) = 0
ORDER BY c.customer_id;
"""

customers_never_delivered = pd.read_sql_query(
    query,
    connection
)

customers_never_delivered

    customer_id    customer_name
0         C0004     Rohan Sharma
1         C0006       Neha Verma
2         C0007   Rahul Deshmukh
3         C0008   Rahul Kulkarni
4         C0009      Arjun Joshi
..          ...              ...
262       C0494      Kavya Singh
263       C0496  Aditya Kulkarni
264       C0497      Rohan Gupta
265       C0498      Karan Gupta
266       C0499      Aarav Singh

[267 rows x 2 columns]

In [128]:
query = """
SELECT
    p.product_id,
    p.product_name,

    SUM(
        CASE
            WHEN oi.quantity > 0
            THEN oi.quantity
            ELSE 0
        END
    ) AS purchase_quantity,

    ABS(
        SUM(
            CASE
                WHEN oi.quantity < 0
                THEN oi.quantity
                ELSE 0
            END
        )
    ) AS return_quantity

FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id

GROUP BY
    p.product_id,
    p.product_name

HAVING return_quantity > purchase_quantity

ORDER BY return_quantity DESC;
"""

products_more_returns = pd.read_sql_query(
    query,
    connection
)

products_more_returns

  product_id product_name  purchase_quantity  return_quantity
0      P0041      Cushion                  0                5
1      P0092       Mobile                  3                5
2      P0107       Mobile                  2                5
3      P0287    Biography                  1                5
4      P0028     Keyboard                  3                4
5      P0086        Shoes                  1                4
6      P0472        Table                  0                3
7      P0448     Textbook                  1                2
8      P0130      T-Shirt                  0                1

In [130]:
query = """
SELECT
    p.category,

    ABS(
        SUM(
            CASE
                WHEN oi.quantity < 0
                THEN oi.quantity
                ELSE 0
            END
        )
    ) AS returned_items,

    SUM(
        ABS(oi.quantity)
    ) AS total_items,

    ROUND(
        100.0 *
        ABS(
            SUM(
                CASE
                    WHEN oi.quantity < 0
                    THEN oi.quantity
                    ELSE 0
                END
            )
        )
        /
        NULLIF(
            SUM(ABS(oi.quantity)),
            0
        ),
        2
    ) AS return_rate_percent

FROM products p

JOIN order_items oi
    ON p.product_id = oi.product_id

GROUP BY p.category

ORDER BY return_rate_percent DESC;
"""

return_rate_by_category = pd.read_sql_query(
    query,
    connection
)

return_rate_by_category

      category  returned_items  total_items  return_rate_percent
0  Electronics              60         1819                 3.30
1        Books              45         1500                 3.00
2     Clothing              42         1410                 2.98
3         Home              34         1197                 2.84

In [132]:
customers_never_delivered.to_csv(
    "reports/customers_never_delivered.csv",
    index=False
)

products_more_returns.to_csv(
    "reports/products_more_returns.csv",
    index=False
)

return_rate_by_category.to_csv(
    "reports/return_rate_by_category.csv",
    index=False
)

print("All intermediate SQL reports saved successfully.")

All intermediate SQL reports saved successfully.

In [134]:
print("========== INTERMEDIATE SQL ANALYSIS ==========\n")

print("Customers who never had a delivered order:")
display(customers_never_delivered.head(10))

print("\nProducts with more returns than purchases:")
display(products_more_returns.head(10))

print("\nReturn rate by category:")
display(return_rate_by_category)

========== INTERMEDIATE SQL ANALYSIS ==========

Customers who never had a delivered order:

  customer_id   customer_name
0       C0004    Rohan Sharma
1       C0006      Neha Verma
2       C0007  Rahul Deshmukh
3       C0008  Rahul Kulkarni
4       C0009     Arjun Joshi
5       C0010  Karan Deshmukh
6       C0011     Aditi Patil
7       C0012   Isha Deshmukh
8       C0013    Aditi Sharma
9       C0014     Arjun Mehta

Products with more returns than purchases:

  product_id product_name  purchase_quantity  return_quantity
0      P0041      Cushion                  0                5
1      P0092       Mobile                  3                5
2      P0107       Mobile                  2                5
3      P0287    Biography                  1                5
4      P0028     Keyboard                  3                4
5      P0086        Shoes                  1                4
6      P0472        Table                  0                3
7      P0448     Textbook                  1                2
8      P0130      T-Shirt                  0                1

Return rate by category:

      category  returned_items  total_items  return_rate_percent
0  Electronics              60         1819                 3.30
1        Books              45         1500                 3.00
2     Clothing              42         1410                 2.98
3         Home              34         1197                 2.84

## 5 — Advanced SQL Analysis

## Advanced Queries (Window Functions, CTEs, Subqueries)

In [137]:
# Running Totals with Window Functions
# Running Total of Revenue by Month
query = """
WITH monthly_revenue AS (
    SELECT
        strftime('%Y-%m', o.order_date) AS order_month,

        SUM(
            oi.quantity *
            oi.unit_price *
            (1 - oi.discount_percent / 100.0)
        ) AS monthly_revenue

    FROM orders o

    JOIN order_items oi
        ON o.order_id = oi.order_id

    GROUP BY order_month
)

SELECT
    order_month,

    ROUND(monthly_revenue, 2)
        AS monthly_revenue,

    ROUND(
        SUM(monthly_revenue) OVER (
            ORDER BY order_month
            ROWS BETWEEN UNBOUNDED PRECEDING
            AND CURRENT ROW
        ),
        2
    ) AS running_total_revenue

FROM monthly_revenue

ORDER BY order_month;
"""

running_revenue = pd.read_sql_query(
    query,
    connection
)

running_revenue

   order_month  monthly_revenue  running_total_revenue
0         None        235470.92              235470.92
1      2025-05        529530.33              765001.25
2      2025-06        790113.38             1555114.63
3      2025-07       1032651.87             2587766.51
4      2025-08       1049245.34             3637011.85
5      2025-09        868958.92             4505970.77
6      2025-10       1163427.42             5669398.19
7      2025-11        840571.01             6509969.21
8      2025-12        926195.22             7436164.43
9      2026-01        836708.26             8272872.69
10     2026-02       1134657.98             9407530.67
11     2026-03        991254.59            10398785.26
12     2026-04       1103732.14            11502517.40
13     2026-05        728207.84            12230725.24
14     2026-06        586318.83            12817044.07
15     2026-07       1173679.44            13990723.51
16     2026-08        188392.26            14179115.78

In [139]:
running_revenue.to_csv(
    "reports/running_revenue.csv",
    index=False
)

print("Running revenue report saved.")

Running revenue report saved.

In [141]:
#8. Ranking with DENSE_RANK
# DENSE_RANK for Top Products
query = """
WITH product_revenue AS (

    SELECT
        p.product_id,
        p.product_name,
        p.category,

        SUM(
            oi.quantity *
            oi.unit_price *
            (1 - oi.discount_percent / 100.0)
        ) AS total_revenue

    FROM products p

    JOIN order_items oi
        ON p.product_id = oi.product_id

    GROUP BY
        p.product_id,
        p.product_name,
        p.category
),

ranked_products AS (

    SELECT
        product_id,
        product_name,
        category,
        ROUND(total_revenue, 2) AS total_revenue,

        DENSE_RANK() OVER (
            PARTITION BY category
            ORDER BY total_revenue DESC
        ) AS revenue_rank

    FROM product_revenue
)

SELECT *
FROM ranked_products

WHERE revenue_rank <= 3

ORDER BY
    category,
    revenue_rank;
"""

top_products_by_category = pd.read_sql_query(
    query,
    connection
)

top_products_by_category

   product_id product_name     category  total_revenue  revenue_rank
0       P0033       Comics        Books      153435.87             1
1       P0049     Textbook        Books       90034.24             2
2       P0085     Textbook        Books       83798.74             3
3       P0251      T-Shirt     Clothing       96220.15             1
4       P0140        Dress     Clothing       90572.83             2
5       P0394      T-Shirt     Clothing       81951.49             3
6       P0177   Headphones  Electronics      113374.37             1
7       P0439   Headphones  Electronics      106030.82             2
8       P0303     Keyboard  Electronics       86154.67             3
9       P0200     Curtains         Home      111677.14             1
10      P0018     Curtains         Home       94424.59             2
11      P0217     Curtains         Home       80584.06             3

In [143]:
top_products_by_category.to_csv(
    "reports/top_products_by_category.csv",
    index=False
)

print("Product ranking report saved.")

Product ranking report saved.

In [145]:
# 9 LAG and LEAD
query = """
WITH monthly_revenue AS (

    SELECT
        strftime('%Y-%m', o.order_date) AS order_month,

        SUM(
            oi.quantity *
            oi.unit_price *
            (1 - oi.discount_percent / 100.0)
        ) AS revenue

    FROM orders o

    JOIN order_items oi
        ON o.order_id = oi.order_id

    GROUP BY order_month
)

SELECT
    order_month,

    ROUND(revenue, 2) AS revenue,

    ROUND(
        LAG(revenue) OVER (
            ORDER BY order_month
        ),
        2
    ) AS previous_month_revenue,

    ROUND(
        LEAD(revenue) OVER (
            ORDER BY order_month
        ),
        2
    ) AS next_month_revenue

FROM monthly_revenue

ORDER BY order_month;
"""

monthly_revenue_comparison = pd.read_sql_query(
    query,
    connection
)

monthly_revenue_comparison

   order_month     revenue  previous_month_revenue  next_month_revenue
0         None   235470.92                     NaN           529530.33
1      2025-05   529530.33               235470.92           790113.38
2      2025-06   790113.38               529530.33          1032651.87
3      2025-07  1032651.87               790113.38          1049245.34
4      2025-08  1049245.34              1032651.87           868958.92
5      2025-09   868958.92              1049245.34          1163427.42
6      2025-10  1163427.42               868958.92           840571.01
7      2025-11   840571.01              1163427.42           926195.22
8      2025-12   926195.22               840571.01           836708.26
9      2026-01   836708.26               926195.22          1134657.98
10     2026-02  1134657.98               836708.26           991254.59
11     2026-03   991254.59              1134657.98          1103732.14
12     2026-04  1103732.14               991254.59           728207.84
13     2026-05   728207.84              1103732.14           586318.83
14     2026-06   586318.83               728207.84          1173679.44
15     2026-07  1173679.44               586318.83           188392.26
16     2026-08   188392.26              1173679.44                 NaN

In [147]:
#Query 10 — Multi-Level CTE
query = """
WITH customer_revenue AS (

    SELECT
        c.customer_id,
        c.customer_name,

        SUM(
            oi.quantity *
            oi.unit_price *
            (1 - oi.discount_percent / 100.0)
        ) AS total_revenue

    FROM customers c

    JOIN orders o
        ON c.customer_id = o.customer_id

    JOIN order_items oi
        ON o.order_id = oi.order_id

    GROUP BY
        c.customer_id,
        c.customer_name
),

customer_ranking AS (

    SELECT
        customer_id,
        customer_name,
        ROUND(total_revenue, 2) AS total_revenue,

        DENSE_RANK() OVER (
            ORDER BY total_revenue DESC
        ) AS customer_rank

    FROM customer_revenue
)

SELECT
    customer_id,
    customer_name,
    total_revenue,
    customer_rank

FROM customer_ranking

WHERE customer_rank <= 10

ORDER BY customer_rank;
"""

customer_ranking = pd.read_sql_query(
    query,
    connection
)

customer_ranking

  customer_id   customer_name  total_revenue  customer_rank
0       C0295     Kavya Verma      217965.86              1
1       C0216  Kavya Deshmukh      177738.03              2
2       C0315     Aditi Singh      148693.73              3
3       C0444     Rohan Patil      147108.06              4
4       C0435     Aarav Gupta      140000.07              5
5       C0381     Pooja Gupta      127714.60              6
6       C0363      Isha Patil      120532.96              7
7       C0324  Karan Deshmukh      116688.01              8
8       C0351     Kavya Mehta      111226.95              9
9       C0233    Aditya Joshi      110281.16             10

In [149]:
customer_ranking.to_csv(
    "reports/customer_ranking.csv",
    index=False
)

print("Customer ranking report saved.")

Customer ranking report saved.

In [151]:
#11 NTILE Customer Segmentation
query = """
WITH customer_revenue AS (

    SELECT
        c.customer_id,
        c.customer_name,

        SUM(
            oi.quantity *
            oi.unit_price *
            (1 - oi.discount_percent / 100.0)
        ) AS total_revenue

    FROM customers c

    JOIN orders o
        ON c.customer_id = o.customer_id

    JOIN order_items oi
        ON o.order_id = oi.order_id

    GROUP BY
        c.customer_id,
        c.customer_name
)

SELECT
    customer_id,
    customer_name,

    ROUND(total_revenue, 2)
        AS total_revenue,

    NTILE(4) OVER (
        ORDER BY total_revenue DESC
    ) AS customer_segment

FROM customer_revenue

ORDER BY customer_segment, total_revenue DESC;
"""

customer_segments = pd.read_sql_query(
    query,
    connection
)

customer_segments.head(20)

   customer_id   customer_name  total_revenue  customer_segment
0        C0295     Kavya Verma      217965.86                 1
1        C0216  Kavya Deshmukh      177738.03                 1
2        C0315     Aditi Singh      148693.73                 1
3        C0444     Rohan Patil      147108.06                 1
4        C0435     Aarav Gupta      140000.07                 1
5        C0381     Pooja Gupta      127714.60                 1
6        C0363      Isha Patil      120532.96                 1
7        C0324  Karan Deshmukh      116688.01                 1
8        C0351     Kavya Mehta      111226.95                 1
9        C0233    Aditya Joshi      110281.16                 1
10       C0453    Aditya Singh      108641.67                 1
11       C0262    Sneha Sharma      105367.59                 1
12       C0071  Pooja Kulkarni      104529.58                 1
13       C0429     Rahul Singh      102520.68                 1
14       C0176    Ananya Gupta      101122.13                 1
15       C0464      Isha Patil      100987.04                 1
16       C0436    Vivaan Joshi       99760.44                 1
17       C0274     Aarav Mehta       96789.57                 1
18       C0350     Aarav Singh       96020.19                 1
19       C0161      Arjun Shah       94244.93                 1

In [153]:
customer_segments.to_csv(
    "reports/customer_segments.csv",
    index=False
)

print("Customer segmentation report saved.")

Customer segmentation report saved.

In [155]:
# 12 Year-over-Year Comparison
query = """
WITH yearly_revenue AS (

    SELECT
        strftime('%Y', o.order_date) AS order_year,

        SUM(
            oi.quantity *
            oi.unit_price *
            (1 - oi.discount_percent / 100.0)
        ) AS revenue

    FROM orders o

    JOIN order_items oi
        ON o.order_id = oi.order_id

    GROUP BY order_year
),

year_comparison AS (

    SELECT
        order_year,
        revenue,

        LAG(revenue) OVER (
            ORDER BY order_year
        ) AS previous_year_revenue

    FROM yearly_revenue
)

SELECT
    order_year,

    ROUND(revenue, 2) AS revenue,

    ROUND(
        previous_year_revenue,
        2
    ) AS previous_year_revenue,

    ROUND(
        100.0 *
        (revenue - previous_year_revenue)
        /
        NULLIF(previous_year_revenue, 0),
        2
    ) AS yoy_growth_percent

FROM year_comparison

ORDER BY order_year;
"""

yoy_analysis = pd.read_sql_query(
    query,
    connection
)

yoy_analysis

  order_year     revenue  previous_year_revenue  yoy_growth_percent
0       None   235470.92                    NaN                 NaN
1       2025  7200693.51              235470.92             2958.00
2       2026  6742951.35             7200693.51               -6.36

In [157]:
yoy_analysis.to_csv(
    "reports/yoy_analysis.csv",
    index=False
)

print("Year-over-year report saved.")

Year-over-year report saved.

In [161]:
### Query 13 — First and Last Purchase Analysis
query = """
WITH customer_orders AS (

    SELECT
        c.customer_id,
        c.customer_name,
        o.order_id,
        date(o.order_date) AS order_date

    FROM customers c

    JOIN orders o
        ON c.customer_id = o.customer_id
)

SELECT
    customer_id,
    customer_name,

    MIN(order_date) AS first_purchase_date,
    MAX(order_date) AS last_purchase_date,

    CAST(
        julianday(MAX(order_date))
        - julianday(MIN(order_date))
        AS INTEGER
    ) AS active_days

FROM customer_orders

GROUP BY
    customer_id,
    customer_name

ORDER BY active_days DESC;
"""

first_last_purchase = pd.read_sql_query(
    query,
    connection
)

first_last_purchase.head(20)

,customer_id,customer_name,first_purchase_date,last_purchase_date,active_days
0,C0140,Rohan Joshi,2025-05-21,2026-07-29,434
1,C0326,Rahul Shah,2025-05-20,2026-07-26,432
2,C0031,Neha Gupta,2025-05-24,2026-07-29,431
3,C0360,Aditi Gupta,2025-05-19,2026-07-20,427
4,C0045,Isha Shah,2025-06-08,2026-08-06,424
5,C0315,Aditi Singh,2025-05-21,2026-07-19,424
6,C0361,Rohan Gupta,2025-05-19,2026-07-17,424
7,C0465,Priya Gupta,2025-06-05,2026-07-30,420
8,C0350,Aarav Singh,2025-05-27,2026-07-11,410
9,C0176,Ananya Gupta,2025-06-02,2026-07-14,407
10,C0300,Ananya Kulkarni,2025-06-15,2026-07-25,405
11,C0381,Pooja Gupta,2025-06-28,2026-08-03,401
12,C0044,Arjun Mehta,2025-07-04,2026-08-03,395
13,C0223,Isha Patil,2025-06-09,2026-07-09,395
14,C0244,Rohan Joshi,2025-06-07,2026-07-07,395
15,C0401,Rahul Gupta,2025-06-20,2026-07-20,395
16,C0464,Isha Patil,2025-06-16,2026-07-15,394
17,C0237,Kavya Kulkarni,2025-07-11,2026-08-06,391
18,C0265,Pooja Sharma,2025-06-08,2026-07-01,388
19,C0445,Kavya Deshmukh,2025-06-28,2026-07-20,387

In [163]:
first_last_purchase.to_csv(
    "reports/first_last_purchase.csv",
    index=False
)

print("First/last purchase report saved.")

First/last purchase report saved.

In [165]:
#Query 14 — Cumulative Distribution
query = """
WITH customer_revenue AS (

    SELECT
        c.customer_id,
        c.customer_name,

        SUM(
            oi.quantity *
            oi.unit_price *
            (1 - oi.discount_percent / 100.0)
        ) AS total_revenue

    FROM customers c

    JOIN orders o
        ON c.customer_id = o.customer_id

    JOIN order_items oi
        ON o.order_id = oi.order_id

    GROUP BY
        c.customer_id,
        c.customer_name
)

SELECT
    customer_id,
    customer_name,

    ROUND(total_revenue, 2)
        AS total_revenue,

    ROUND(
        CUME_DIST() OVER (
            ORDER BY total_revenue
        ),
        4
    ) AS cumulative_distribution

FROM customer_revenue

ORDER BY total_revenue;
"""

cumulative_distribution = pd.read_sql_query(
    query,
    connection
)

cumulative_distribution.head(20)

   customer_id    customer_name  total_revenue  cumulative_distribution
0        C0147       Isha Gupta      -19018.37                   0.0025
1        C0142      Rohan Mehta      -15966.05                   0.0049
2        C0092      Aarav Joshi      -13018.91                   0.0074
3        C0479      Rahul Patil       -7215.44                   0.0099
4        C0209      Priya Joshi       -6302.42                   0.0123
5        C0131      Karan Gupta        -928.98                   0.0148
6        C0008   Rahul Kulkarni          10.04                   0.0172
7        C0240       Neha Patil         381.30                   0.0197
8        C0212       Neha Joshi         546.96                   0.0222
9        C0155      Sneha Patil         569.72                   0.0246
10       C0282      Rahul Singh         592.67                   0.0271
11       C0370       Priya Shah         671.72                   0.0296
12       C0005       Priya Shah         704.32                   0.0320
13       C0493     Arjun Sharma        1023.90                   0.0345
14       C0239      Arjun Patil        1076.77                   0.0369
15       C0167   Rohan Kulkarni        1335.22                   0.0394
16       C0362      Arjun Joshi        1840.74                   0.0419
17       C0253  Aditya Kulkarni        1860.27                   0.0443
18       C0053      Priya Gupta        2201.83                   0.0468
19       C0055       Aditi Shah        2226.54                   0.0493

In [167]:
cumulative_distribution.to_csv(
    "reports/cumulative_distribution.csv",
    index=False
)

print("Cumulative distribution report saved.")

Cumulative distribution report saved.

In [169]:
#Query 15 — Cohort Analysis
query = """
WITH customer_first_purchase AS (

    SELECT
        customer_id,
        MIN(date(order_date)) AS first_purchase_date

    FROM orders

    WHERE customer_id IS NOT NULL

    GROUP BY customer_id
),

customer_cohorts AS (

    SELECT
        customer_id,

        strftime(
            '%Y-%m',
            first_purchase_date
        ) AS cohort_month

    FROM customer_first_purchase
),

customer_activity AS (

    SELECT DISTINCT
        o.customer_id,

        strftime(
            '%Y-%m',
            o.order_date
        ) AS activity_month

    FROM orders o

    WHERE o.customer_id IS NOT NULL
),

cohort_activity AS (

    SELECT
        cc.cohort_month,
        ca.activity_month,
        COUNT(DISTINCT ca.customer_id)
            AS active_customers

    FROM customer_cohorts cc

    JOIN customer_activity ca
        ON cc.customer_id = ca.customer_id

    GROUP BY
        cc.cohort_month,
        ca.activity_month
)

SELECT
    cohort_month,
    activity_month,
    active_customers

FROM cohort_activity

ORDER BY
    cohort_month,
    activity_month;
"""

cohort_analysis = pd.read_sql_query(
    query,
    connection
)

cohort_analysis.head(30)

   cohort_month activity_month  active_customers
0       2025-05        2025-05                45
1       2025-05        2025-06                10
2       2025-05        2025-07                 6
3       2025-05        2025-08                 5
4       2025-05        2025-09                 9
5       2025-05        2025-10                 7
6       2025-05        2025-11                10
7       2025-05        2025-12                 6
8       2025-05        2026-01                 6
9       2025-05        2026-02                 5
10      2025-05        2026-03                 3
11      2025-05        2026-04                 4
12      2025-05        2026-05                 3
13      2025-05        2026-06                 5
14      2025-05        2026-07                 7
15      2025-06        2025-06                53
16      2025-06        2025-07                 7
17      2025-06        2025-08                 5
18      2025-06        2025-09                 7
19      2025-06        2025-10                 6
20      2025-06        2025-11                 3
21      2025-06        2025-12                 6
22      2025-06        2026-01                 8
23      2025-06        2026-02                 8
24      2025-06        2026-03                 7
25      2025-06        2026-04                 6
26      2025-06        2026-05                 8
27      2025-06        2026-06                 6
28      2025-06        2026-07                11
29      2025-06        2026-08                 2

In [171]:
cohort_analysis.to_csv(
    "reports/cohort_analysis.csv",
    index=False
)

print("Cohort analysis report saved.")

Cohort analysis report saved.

In [173]:
### Query 16 — Consecutive-Month Customer Activity
query = """
WITH customer_months AS (

    SELECT DISTINCT
        customer_id,
        strftime('%Y-%m', order_date) AS order_month

    FROM orders

    WHERE customer_id IS NOT NULL
),

numbered_months AS (

    SELECT
        customer_id,
        order_month,

        LAG(order_month) OVER (
            PARTITION BY customer_id
            ORDER BY order_month
        ) AS previous_order_month

    FROM customer_months
)

SELECT
    customer_id,
    order_month,
    previous_order_month

FROM numbered_months

WHERE previous_order_month IS NOT NULL

ORDER BY
    customer_id,
    order_month;
"""

consecutive_activity = pd.read_sql_query(
    query,
    connection
)

consecutive_activity.head(30)

   customer_id order_month previous_order_month
0        C0002     2026-07              2025-11
1        C0003     2026-03              2025-06
2        C0003     2026-04              2026-03
3        C0004     2025-11              2025-05
4        C0004     2025-12              2025-11
5        C0006     2025-11              2025-05
6        C0007     2026-02              2025-08
7        C0009     2025-10              2025-07
8        C0010     2025-11              2025-10
9        C0014     2026-03              2025-07
10       C0015     2025-08              2025-07
11       C0017     2026-02              2025-07
12       C0018     2026-06              2026-03
13       C0019     2026-08              2025-07
14       C0021     2025-10              2025-08
15       C0021     2026-04              2025-10
16       C0021     2026-05              2026-04
17       C0022     2026-04              2025-11
18       C0025     2025-11              2025-08
19       C0027     2025-10              2025-08
20       C0027     2026-07              2025-10
21       C0031     2025-08              2025-05
22       C0031     2025-09              2025-08
23       C0031     2026-07              2025-09
24       C0032     2026-04              2025-08
25       C0032     2026-08              2026-04
26       C0033     2026-06              2026-02
27       C0035     2025-08              2025-07
28       C0037     2025-11              2025-09
29       C0038     2025-12              2025-05

In [175]:
consecutive_activity.to_csv(
    "reports/consecutive_customer_activity.csv",
    index=False
)

print("Consecutive activity report saved.")

Consecutive activity report saved.

In [177]:
print("1. Running Revenue:")
display(running_revenue.head(5))

print("\n2. Top Products by Category:")
display(top_products_by_category.head(10))

print("\n3. Monthly Revenue Comparison:")
display(monthly_revenue_comparison.head(5))

print("\n4. Customer Ranking:")
display(customer_ranking.head(10))

print("\n5. Customer Segmentation:")
display(customer_segments.head(10))

print("\n6. Year-over-Year Analysis:")
display(yoy_analysis)

print("\n7. First/Last Purchase:")
display(first_last_purchase.head(5))

print("\n8. Cumulative Distribution:")
display(cumulative_distribution.head(5))

print("\n9. Cohort Analysis:")
display(cohort_analysis.head(10))

print("\n10. Consecutive Customer Activity:")
display(consecutive_activity.head(10))

1. Running Revenue:

  order_month  monthly_revenue  running_total_revenue
0        None        235470.92              235470.92
1     2025-05        529530.33              765001.25
2     2025-06        790113.38             1555114.63
3     2025-07       1032651.87             2587766.51
4     2025-08       1049245.34             3637011.85

2. Top Products by Category:

  product_id product_name     category  total_revenue  revenue_rank
0      P0033       Comics        Books      153435.87             1
1      P0049     Textbook        Books       90034.24             2
2      P0085     Textbook        Books       83798.74             3
3      P0251      T-Shirt     Clothing       96220.15             1
4      P0140        Dress     Clothing       90572.83             2
5      P0394      T-Shirt     Clothing       81951.49             3
6      P0177   Headphones  Electronics      113374.37             1
7      P0439   Headphones  Electronics      106030.82             2
8      P0303     Keyboard  Electronics       86154.67             3
9      P0200     Curtains         Home      111677.14             1

3. Monthly Revenue Comparison:

  order_month     revenue  previous_month_revenue  next_month_revenue
0        None   235470.92                     NaN           529530.33
1     2025-05   529530.33               235470.92           790113.38
2     2025-06   790113.38               529530.33          1032651.87
3     2025-07  1032651.87               790113.38          1049245.34
4     2025-08  1049245.34              1032651.87           868958.92

4. Customer Ranking:

  customer_id   customer_name  total_revenue  customer_rank
0       C0295     Kavya Verma      217965.86              1
1       C0216  Kavya Deshmukh      177738.03              2
2       C0315     Aditi Singh      148693.73              3
3       C0444     Rohan Patil      147108.06              4
4       C0435     Aarav Gupta      140000.07              5
5       C0381     Pooja Gupta      127714.60              6
6       C0363      Isha Patil      120532.96              7
7       C0324  Karan Deshmukh      116688.01              8
8       C0351     Kavya Mehta      111226.95              9
9       C0233    Aditya Joshi      110281.16             10

5. Customer Segmentation:

  customer_id   customer_name  total_revenue  customer_segment
0       C0295     Kavya Verma      217965.86                 1
1       C0216  Kavya Deshmukh      177738.03                 1
2       C0315     Aditi Singh      148693.73                 1
3       C0444     Rohan Patil      147108.06                 1
4       C0435     Aarav Gupta      140000.07                 1
5       C0381     Pooja Gupta      127714.60                 1
6       C0363      Isha Patil      120532.96                 1
7       C0324  Karan Deshmukh      116688.01                 1
8       C0351     Kavya Mehta      111226.95                 1
9       C0233    Aditya Joshi      110281.16                 1

6. Year-over-Year Analysis:

  order_year     revenue  previous_year_revenue  yoy_growth_percent
0       None   235470.92                    NaN                 NaN
1       2025  7200693.51              235470.92             2958.00
2       2026  6742951.35             7200693.51               -6.36

7. First/Last Purchase:

,customer_id,customer_name,first_purchase_date,last_purchase_date,active_days
0,C0140,Rohan Joshi,2025-05-21,2026-07-29,434
1,C0326,Rahul Shah,2025-05-20,2026-07-26,432
2,C0031,Neha Gupta,2025-05-24,2026-07-29,431
3,C0360,Aditi Gupta,2025-05-19,2026-07-20,427
4,C0045,Isha Shah,2025-06-08,2026-08-06,424

8. Cumulative Distribution:

  customer_id customer_name  total_revenue  cumulative_distribution
0       C0147    Isha Gupta      -19018.37                   0.0025
1       C0142   Rohan Mehta      -15966.05                   0.0049
2       C0092   Aarav Joshi      -13018.91                   0.0074
3       C0479   Rahul Patil       -7215.44                   0.0099
4       C0209   Priya Joshi       -6302.42                   0.0123

9. Cohort Analysis:

  cohort_month activity_month  active_customers
0      2025-05        2025-05                45
1      2025-05        2025-06                10
2      2025-05        2025-07                 6
3      2025-05        2025-08                 5
4      2025-05        2025-09                 9
5      2025-05        2025-10                 7
6      2025-05        2025-11                10
7      2025-05        2025-12                 6
8      2025-05        2026-01                 6
9      2025-05        2026-02                 5

10. Consecutive Customer Activity:

  customer_id order_month previous_order_month
0       C0002     2026-07              2025-11
1       C0003     2026-03              2025-06
2       C0003     2026-04              2026-03
3       C0004     2025-11              2025-05
4       C0004     2025-12              2025-11
5       C0006     2025-11              2025-05
6       C0007     2026-02              2025-08
7       C0009     2025-10              2025-07
8       C0010     2025-11              2025-10
9       C0014     2026-03              2025-07

## Python + SQL Reporting Tool

In [184]:
def generate_report(report_type, start_date, end_date):

    if report_type.lower() not in ["daily", "weekly", "monthly"]:
        print("Invalid report type.")
        print("Choose: daily, weekly, or monthly")
        return

    query = """
    SELECT
        COUNT(DISTINCT o.order_id) AS total_orders,

        ROUND(
            SUM(
                oi.quantity *
                oi.unit_price *
                (1 - oi.discount_percent / 100.0)
            ),
            2
        ) AS total_revenue,

        SUM(
            CASE
                WHEN oi.quantity < 0
                THEN ABS(oi.quantity)
                ELSE 0
            END
        ) AS returned_items

    FROM orders o

    JOIN order_items oi
        ON o.order_id = oi.order_id

    WHERE date(o.order_date)
          BETWEEN date(?) AND date(?);
    """

    result = pd.read_sql_query(
        query,
        connection,
        params=[start_date, end_date]
    )

    print("\n================================")
    print("       E-COMMERCE REPORT")
    print("================================")
    print("Report Type :", report_type.upper())
    print("Start Date  :", start_date)
    print("End Date    :", end_date)
    print("--------------------------------")

    print(
        "Total Orders :",
        result["total_orders"].iloc[0]
    )

    print(
        "Total Revenue:",
        result["total_revenue"].iloc[0]
    )

    print(
        "Returned Items:",
        result["returned_items"].iloc[0]
    )

    print("================================\n")

    return result

In [186]:
date_range = pd.read_sql_query(
    """
    SELECT
        MIN(date(order_date)) AS first_date,
        MAX(date(order_date)) AS last_date
    FROM orders;
    """,
    connection
)

date_range

   first_date   last_date
0  2025-05-15  2026-08-08

In [188]:
generate_report(
    "monthly",
    "2026-07-01",
    "2026-07-31"
)

================================
       E-COMMERCE REPORT
================================
Report Type : MONTHLY
Start Date  : 2026-07-01
End Date    : 2026-07-31
--------------------------------
Total Orders : 61
Total Revenue: 1173679.44
Returned Items: 9
================================

   total_orders  total_revenue  returned_items
0            61     1173679.44               9

In [190]:
report_type = input(
    "Enter report type (daily/weekly/monthly): "
)

start_date = input(
    "Enter start date (YYYY-MM-DD): "
)

end_date = input(
    "Enter end date (YYYY-MM-DD): "
)

generate_report(
    report_type,
    start_date,
    end_date
)

Enter report type (daily/weekly/monthly):  monthly
Enter start date (YYYY-MM-DD):  2025-05-15
Enter end date (YYYY-MM-DD):  2026-08-08

================================
       E-COMMERCE REPORT
================================
Report Type : MONTHLY
Start Date  : 2025-05-15
End Date    : 2026-08-08
--------------------------------
Total Orders : 860
Total Revenue: 13943644.85
Returned Items: 181
================================

   total_orders  total_revenue  returned_items
0           860    13943644.85             181

## Part 5 — Edge Case Handling

In [193]:
import sqlite3
from datetime import datetime

In [195]:
def test_invalid_order_reference():
    conn = sqlite3.connect(":memory:")
    cursor = conn.cursor()

    # Create tables
    cursor.execute("""
        CREATE TABLE orders (
            order_id TEXT PRIMARY KEY
        )
    """)

    cursor.execute("""
        CREATE TABLE order_items (
            order_id TEXT,
            product_id TEXT,
            quantity INTEGER
        )
    """)

    # Valid orders
    cursor.executemany(
        "INSERT INTO orders VALUES (?)",
        [
            ("ORD001",),
            ("ORD002",)
        ]
    )

    # One valid and one invalid order reference
    cursor.executemany(
        "INSERT INTO order_items VALUES (?, ?, ?)",
        [
            ("ORD001", "P001", 2),
            ("ORD999", "P002", 1)
        ]
    )

    # Find invalid references
    cursor.execute("""
        SELECT oi.order_id
        FROM order_items oi
        LEFT JOIN orders o
            ON oi.order_id = o.order_id
        WHERE o.order_id IS NULL
    """)

    invalid_orders = cursor.fetchall()

    conn.close()

    assert len(invalid_orders) == 1
    assert invalid_orders[0][0] == "ORD999"

    print("PASS: Invalid order_id was detected.")

In [197]:
test_invalid_order_reference()

PASS: Invalid order_id was detected.

In [199]:
def test_discount_greater_than_100():
    discount_percent = 150

    assert discount_percent <= 100, \
        "Invalid discount: discount_percent cannot be greater than 100"

    print("PASS: Invalid discount was handled.")

In [201]:
def test_discount_greater_than_100():
    discount_percent = 150

    if discount_percent > 100:
        result = "INVALID"
    else:
        result = "VALID"

    assert result == "INVALID"

    print("PASS: Discount greater than 100 was rejected.")

In [203]:
test_discount_greater_than_100()

PASS: Discount greater than 100 was rejected.

In [205]:
#Test 3 — Quantity = 0
def test_zero_quantity():
    quantity = 0
    unit_price = 1000
    discount_percent = 10

    revenue = (
        quantity
        * unit_price
        * (1 - discount_percent / 100)
    )

    assert revenue == 0

    print("PASS: Zero quantity results in zero revenue.")

In [208]:
test_zero_quantity()

PASS: Zero quantity results in zero revenue.

In [212]:
#Test 4 — Future order date
def test_future_order_date():
    future_date = "2099-01-01 10:30:00"

    order_datetime = datetime.strptime(
        future_date,
        "%Y-%m-%d %H:%M:%S"
    )

    current_datetime = datetime.now()

    assert order_datetime > current_datetime

    print("PASS: Future order date was detected.")

In [214]:
test_future_order_date()

PASS: Future order date was detected.

In [216]:
#Step 5 — Run all tests together
def run_all_edge_case_tests():

    print("========== EDGE CASE TESTING ==========\n")

    test_invalid_order_reference()

    test_discount_greater_than_100()

    test_zero_quantity()

    test_future_order_date()

    print("\n========== ALL EDGE CASE TESTS PASSED ==========")


run_all_edge_case_tests()

========== EDGE CASE TESTING ==========

PASS: Invalid order_id was detected.
PASS: Discount greater than 100 was rejected.
PASS: Zero quantity results in zero revenue.
PASS: Future order date was detected.

========== ALL EDGE CASE TESTS PASSED ==========